name: steam_games
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 상태 관리
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # 라우팅
  go_router: ^12.0.0
  
  # API 통신
  http: ^1.1.0
  dio: ^5.4.0  # 더 강력한 HTTP 클라이언트
  
  # JSON 처리
  json_annotation: ^4.8.0
  freezed_annotation: ^2.4.0  # 불변 모델
  
  # 로컬 저장소
  shared_preferences: ^2.2.2

  # 차트 (통계 화면용)
  fl_chart: ^0.65.0
  
  # 이미지 캐싱
  cached_network_image: ^3.3.0


dev_dependencies:
  # 코드 생성
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  freezed: ^2.4.0
  riverpod_generator: ^2.3.0


  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
